name: Corelab
favicon: null
layout_spectrum: 0.7884108272846788
typography_spectrum: 0.5905547318980098
title: Corelab - Social Change Workshop
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.26056488370522857
  lightness: 0.36077321670018137
  saturation: 0.30499530932866037
  rhythmicContrast: 0.2317644814029336
purpose: []
